import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "./Providers";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/toaster";
import Sidebar from "./_components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Sidebar />
          <div className="fixed left-[280px] right-0">{children}</div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
